### ISSUE TITLE
[Enhancement] Added compatibility with OpenBodyCams

### ISSUE THREAD

**Issue by PickeBlind** [lammas321/lammOS-LethalCompany#1]
Pretty much what the title says. It would be nice if this mod was compatible with OpenBodyCams, as it is with HelmetCameras. If it already is, then I'm sorry for this issue.

**Comment by lammas321** [comment]
I was actually planning to do so after I released v1.2.1, hence why it wasn't in the What's Planned section of the readme lol. It'll be compatible with RickArg's HelmetCameras, Solos_Bodycams, and OpenBodyCams in the next update
