### ISSUE TITLE
[Mod Incompatibility - v1.3.1] TooManyEmotes and lammOS

### ISSUE THREAD

**Issue by SeedyMcSeedface** [lammas321/lammOS-LethalCompany#4]
When lammOS is installed and enabled, the changes it does prevents [TooManyEmotes](https://thunderstore.io/c/lethal-company/p/FlipMods/TooManyEmotes/)' emotes store from displaying properly.

As a reference - this is what it should look like:
![1966720_20240130231502_1](https://github.com/lammas321/lammOS-LethalCompany/assets/155770932/53012946-c90f-42bb-be6e-4e2a090a947c)
I am unsure if there's anything of help in the log files, but here's the one while running without lammOS active: [LogOutput without lammOS.log](https://github.com/lammas321/lammOS-LethalCompany/files/14107078/LogOutput.without.lammOS.log)

This is what it looks like with lammOS installed and enabled:
![1966720_20240130231223_1](https://github.com/lammas321/lammOS-LethalCompany/assets/155770932/70c8a9f4-f106-40d4-820f-a357759dd5cb)
Log with lammOS active: [LogOutput with lammOS.log](https://github.com/lammas321/lammOS-LethalCompany/files/14107082/LogOutput.with.lammOS.log)

The code for the profile I used for testing is: 018d5dba-98ef-fa92-98d1-18dd53499a72
All configs are set to default settings with the exception of BepInEx's config being configured for more detailed logging.

I'm assuming the reason for this is due to one of the changes you made with how the terminal works.
It's a minor issue, as everything else seems to work fine as far as I can tell.

If there's anything else I can provide to help please let me know.

**Comment by lammas321** [comment]
It looks like TooManyEmotes is using the Terminal.TextPostProcess method. Go to lammOS's config and set the config option at the very bottom to false, then either restart Lethal or type reload in the terminal. This should fix the missing text

**Comment by SeedyMcSeedface** [comment]
That worked.
It displays normally now with that change.

**Comment by lammas321** [comment]
That's good to hear. lammOS doesn't use that method at all, and thus can be more performant with it disabled, but other mods may still use it, such as TooManyEmotes, so I have it as a config option for compatibility

**Comment by SeedyMcSeedface** [comment]
Yeah I had no idea if that was what was causing it to not work or not, so I figured I'd bring it up so I could find out for sure.

Anyway, this can be closed when ready. Thanks for the help.

**Comment by lammas321** [comment]
No problem!
